### ISSUE TITLE
Problem when analyzing linux

### ISSUE THREAD

**Issue by iwangshuo** [jjhenkel/c2ocaml#1]
when I used command "make linux", I found a problem. 
terminal display this:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  LD      Documentation/video4linux/built-in.o
  LINK    vmlinux
  LD      vmlinux.o
  MODPOST vmlinux.o
  GEN     .version
  CHK     include/generated/compile.h
  UPD     include/generated/compile.h
  CC      init/version.o
  LD      init/built-in.o
arch/x86/kernel/head64.o: In function `_GLOBAL__sub_D_00100_1_early_pmd_flags':
head64.c:(.text.exit+0x5): undefined reference to `__gcov_exit'
arch/x86/kernel/head.o: In function `_GLOBAL__sub_D_00100_1_reserve_ebda_region':
head.c:(.text.exit+0x5): undefined reference to `__gcov_exit'
init/built-in.o: In function `_GLOBAL__sub_D_00100_1___ksymtab_system_state':
main.c:(.text.exit+0x5): undefined reference to `__gcov_exit'
init/built-in.o: In function `_GLOBAL__sub_D_00100_1_root_mountflags':
do_mounts.c:(.text.exit+0x3e): undefined reference to `__gcov_exit'
init/built-in.o: In function `_GLOBAL__sub_D_00100_1_rd_prompt':
do_mounts_rd.c:(.text.exit+0x60): undefined reference to `__gcov_exit'
init/built-in.o:do_mounts_initrd.c:(.text.exit+0x82): more undefined references to `__gcov_exit' follow
Makefile:916: recipe for target 'vmlinux' failed
make: *** [vmlinux] Error 1
/
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Sorry, I do not know how to solve this. I would appreciate it if you could give me a hand!!!

**Comment by jjhenkel** [comment]
Hi @iwangshuo ,

I just realized this issue was out here---for some reason my GitHub user wast set to 'watch' these two submodules for issues/etc.

I realize this is quite some time ago---if this is something you're still looking at could you give me a little more detail as to what commands you were running when this happened? An error in the build doesn't necessarily stop `c2ocaml` from generating files so this might have been a non-issue (especially if it is happening during linking).

**Comment by iwangshuo** [comment]
@jjhenkel thanks for your reply!
At the beginning, I thought this error might stop c2ocaml. Then I checked the output directory and found ocaml files were already there! So you're right, it is a non-issue

**Comment by jjhenkel** [comment]
@iwangshuo Great thanks for letting me know (and helping me realize I wasn't watching this repo)!
